# Generated by Django 4.2.20 on 2025-04-06 16:31

from django.db import migrations, models
import django.utils.timezone
import sudoku.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedsudoku',
            name='board',
            field=models.JSONField(default=sudoku.models.get_empty_board),
        ),
        migrations.AlterField(
            model_name='solvedsudoku',
            name='date_solved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solvedsudoku',
            name='solution',
            field=models.JSONField(default=sudoku.models.get_empty_board),
        ),
    ]
