# Generated by Django 4.2.20 on 2025-04-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='color_scheme',
            field=models.CharField(default='light', max_length=50),
        ),
    ]
